#!/usr/bin/env python3
"""Start official lichess-bot for Raja or Nero.

Same Boardman brain as the webhook. Separate Lichess BOT account + token
per agent. One account cannot play both sides.

  python3 builders/lichess_bots/run.py --agent raja
  python3 builders/lichess_bots/run.py --agent nero

Tokens (never written to config.yml):
  Raja: LICHESS_API_TOKEN / LICHESS_BOT_TOKEN
  Nero: LICHESS_NERO_API_TOKEN
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CLONE = ROOT / "third_party" / "lichess-bot"
ENV_FILE = ROOT / ".env"

AGENTS = {
    "raja": {
        "username": "myrajafromboardman",
        "uci": ROOT / "builders" / "lichess_raja" / "raja_uci.py",
        "hello": "Raja — Boardman agent. Good luck.",
        "token_keys": ("LICHESS_RAJA_API_TOKEN", "LICHESS_BOT_TOKEN", "LICHESS_API_TOKEN"),
    },
    "nero": {
        "username": os.environ.get("NERO_LICHESS_USER") or "keniichii",
        "uci": ROOT / "builders" / "lichess_nero" / "nero_uci.py",
        "hello": "Nero — Boardman agent. Good luck.",
        "token_keys": (
            "LICHESS_NERO_API_TOKEN",
            "LICHESS_API_TOKEN_NERO",
            "LICHESS_BOT_TOKEN_NERO",
            "NERO_LICHESS_API_TOKEN",
        ),
    },
}


def _load_dotenv(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _token_for(agent: str, file_env: dict[str, str], env: dict[str, str]) -> str:
    for key in AGENTS[agent]["token_keys"]:
        val = (env.get(key) or file_env.get(key) or "").strip()
        if val:
            return val
    return ""


def _write_config(agent: str, username: str) -> Path:
    spec = AGENTS[agent]
    uci = spec["uci"]
    cfg = CLONE / f"config-{agent}.yml"
    cfg.write_text(
        f"""# Generated by builders/lichess_bots/run.py — token from env, not this file.
token: "from-env"
url: "https://lichess.org/"

engine:
  dir: "{uci.parent}"
  name: "{uci.name}"
  protocol: "uci"
  interpreter: "{sys.executable}"
  working_dir: "{ROOT}"
  ponder: false
  silence_stderr: true
  debug: false
  uci_options: {{}}

abort_time: 30
fake_think_time: false
rate_limiting_delay: 0
move_overhead: 2000
max_takebacks_accepted: 0
quit_after_all_games_finish: false

correspondence:
  move_time: 60
  checkin_period: 600
  disconnect_time: 300
  ponder: false

challenge:
  concurrency: 1
  sort_by: "first"
  accept_bot: true
  only_bot: false
  max_increment: 20
  min_increment: 0
  max_base: 1800
  min_base: 15
  variants:
    - standard
  time_controls:
    - bullet
    - blitz
    - rapid
  modes:
    - casual
    - rated

greeting:
  hello: "{spec['hello']}"
  goodbye: "Good game."
  hello_spectators: "Watching {agent.title()} (Boardman)."
  goodbye_spectators: "Thanks for watching."

pgn_directory: "{CLONE / 'games' / agent}"
pgn_file_grouping: "all"

matchmaking:
  allow_matchmaking: {str(os.getenv("LICHESS_MATCHMAKING", "")).strip().lower() in {"1", "true", "yes"}}
""",
        encoding="utf-8",
    )
    return cfg


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run lichess-bot for a Boardman agent")
    parser.add_argument("--agent", choices=sorted(AGENTS), default="raja")
    args = parser.parse_args(argv)

    env = dict(os.environ)
    file_env = _load_dotenv(ENV_FILE)
    spec = AGENTS[args.agent]
    username = str(spec["username"])
    if args.agent == "nero":
        username = (
            env.get("NERO_LICHESS_USER")
            or file_env.get("NERO_LICHESS_USER")
            or username
        )
        AGENTS["nero"]["username"] = username

    token = _token_for(args.agent, file_env, env)
    if not token:
        keys = ", ".join(spec["token_keys"])
        print(f"missing {keys} in .env for {args.agent}", file=sys.stderr)
        return 1
    if not (CLONE / "lichess-bot.py").is_file():
        print(
            f"clone lichess-bot first: git clone https://github.com/lichess-bot-devs/lichess-bot.git {CLONE}",
            file=sys.stderr,
        )
        return 1
    if not Path(spec["uci"]).is_file():
        print(f"missing UCI adapter {spec['uci']}", file=sys.stderr)
        return 1

    cfg = _write_config(args.agent, username)
    env["LICHESS_BOT_TOKEN"] = token
    env["PYTHONPATH"] = str(ROOT) + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    env["STOCKFISH_PATH"] = env.get("STOCKFISH_PATH") or str(ROOT / "engines" / "stockfish")
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    try:
        from gaming.src.stack.agentic.registry import get_registry
        from gaming.src.stack.agentic.lichess_identity import bind_agent

        aid = (
            "agent_raja_kia_alekhine"
            if args.agent == "raja"
            else "agent_nero_sicilian_french"
        )
        bind_agent(get_registry(), aid, live=True, env={**env, **file_env})
    except Exception as exc:
        print(f"boardman identity bind skipped: {exc}", file=sys.stderr)
    print(f"starting lichess-bot for {args.agent} → https://lichess.org/@/{username}")
    print("Lichess is the gym. Boardman webhook (Raja :18761 / Nero :18762) is the wallet venue.")
    return subprocess.call(
        [sys.executable, str(CLONE / "lichess-bot.py"), "--config", str(cfg)],
        cwd=str(CLONE),
        env=env,
    )


if __name__ == "__main__":
    raise SystemExit(main())
