#!/usr/bin/env python3
"""
Generate onile / game-center onboarding kit:
  - QR PNGs (or .url.txt fallback) per partner code
  - Printable one-pager (Markdown)
  - Links index

Usage:
  PYTHONPATH=src:gaming:. python scripts/generate_onile_kit.py
  PYTHONPATH=src:gaming:. python scripts/generate_onile_kit.py --out data/onile_kit
  PYTHONPATH=src:gaming:. python scripts/generate_onile_kit.py --code IKEJA01
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))


def _write_qr(path: Path, url: str) -> str:
    """Write QR PNG. Returns method used."""
    # 1) qrcode lib
    try:
        import qrcode

        img = qrcode.make(url)
        path.parent.mkdir(parents=True, exist_ok=True)
        img.save(str(path))
        return "qrcode"
    except Exception:
        pass

    # 2) download free QR API (optional network)
    try:
        import urllib.parse
        import urllib.request

        q = urllib.parse.quote(url, safe="")
        api = f"https://api.qrserver.com/v1/create-qr-code/?size=400x400&data={q}"
        path.parent.mkdir(parents=True, exist_ok=True)
        urllib.request.urlretrieve(api, str(path))
        return "api.qrserver.com"
    except Exception:
        pass

    # 3) URL text only
    path.parent.mkdir(parents=True, exist_ok=True)
    url_path = path.with_suffix(".url.txt")
    url_path.write_text(url + "\n", encoding="utf-8")
    return "url.txt"


ONE_PAGER = """# Boardman desk card — {name}

**Area:** {area} · **Code:** `{code}`

## For players (30 seconds)

1. **Scan the QR** (or open the link below)
2. **Get money** if your balance is empty (₦ Paystack / USDC)
3. **Challenge** the person next to you — or join tonight’s **Cup**
4. Both **Lock** (1v1) · for cups, entry locks into the pot
5. **Play** on the shop console / phone / table (Chess, Ludo, Monopoly…)
6. Both **Report result** (photo + I won / I lost) → winner is paid

## Desk QR (this shop)

```
{url}
```

Print the PNG in this folder on the wall / counter.

## Friday cup (ops)

Host creates:

```
/tcreate 8 5 physical.chess {name} Friday --center={code}
```

Share cup QR: `t.me/<bot>?start=cup_<CODE>`

## Economics

- Players pay **normal stakes** — no extra “shop tax”
- This center earns **~1.5%** of matched volume from Boardman platform fee
- Cups: entry pool → 1st / 2nd / 3rd after fee

## Support

Telegram bot · Boardman by sideQuest · boardman.playingsidequest.fun

*Scan · Lock · Play · Settle*
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate onile partner kit")
    ap.add_argument("--out", default=str(ROOT / "data" / "onile_kit"))
    ap.add_argument("--code", default="", help="Only one partner code")
    ap.add_argument(
        "--bot-url",
        default="",
        help="Override bot base URL (default TELEGRAM_BOT_URL / myboardmanOfficialBot)",
    )
    args = ap.parse_args()

    from gaming.src.backend.services.partners import (
        list_partners,
        partner_start_url,
        reload_partners,
    )

    reload_partners()
    partners = list_partners(partner_type="center", active_only=True)
    if args.code:
        partners = [p for p in partners if p.get("code") == args.code.upper()]
        if not partners:
            print(f"No partner {args.code}", file=sys.stderr)
            return 1

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    index_lines = [
        "# Onile kit index",
        "",
        "Generated by `scripts/generate_onile_kit.py`",
        "",
        "| Code | Name | Area | Deep link |",
        "|------|------|------|-----------|",
    ]

    for p in partners:
        code = p["code"]
        folder = out / code
        folder.mkdir(parents=True, exist_ok=True)
        url = partner_start_url(code, bot_url=args.bot_url or None)
        method = _write_qr(folder / "qr.png", url)
        (folder / "DESK_CARD.md").write_text(
            ONE_PAGER.format(
                name=p.get("display_name") or code,
                area=p.get("area") or p.get("city") or "Lagos",
                code=code,
                url=url,
            ),
            encoding="utf-8",
        )
        (folder / "link.txt").write_text(url + "\n", encoding="utf-8")
        index_lines.append(
            f"| `{code}` | {p.get('display_name')} | {p.get('area') or p.get('city')} | `{url}` |"
        )
        print(f"  {code}: QR via {method} → {folder}")

    # Shared one-pager for all shops
    (out / "README.md").write_text(
        "\n".join(
            [
                "# Onile / game center kit (Lagos)",
                "",
                "Each folder is one shop: **qr.png** + **DESK_CARD.md** + **link.txt**.",
                "",
                "1. Print `qr.png` (A5 or sticker)",
                "2. Hand owner `DESK_CARD.md` (or PDF it)",
                "3. Train desk once: Scan → Get money → Challenge / Cup → Lock → Play → Report",
                "",
                "Docs: `docs/ONILE_GAME_CENTERS.md`",
                "",
            ]
            + index_lines
            + ["", "## Commands", "", "```bash", "python scripts/generate_onile_kit.py", "```", ""]
        ),
        encoding="utf-8",
    )

    # Master printable
    (out / "ONE_PAGER_GENERIC.md").write_text(
        ONE_PAGER.format(
            name="Your Game Center",
            area="Lagos",
            code="YOURCODE",
            url="https://t.me/myboardmanOfficialBot?start=ctr_YOURCODE",
        ),
        encoding="utf-8",
    )

    print(f"\nDone → {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
